<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>serverdesk-agent</AssemblyName>
    <RootNamespace>ServerDesk.Agent</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServerDesk.Agent.Contracts\ServerDesk.Agent.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
  </ItemGroup>
</Project>
