<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServerDesk.Application\ServerDesk.Application.csproj" />
    <ProjectReference Include="..\ServerDesk.Domain\ServerDesk.Domain.csproj" />
  </ItemGroup>
</Project>
